version: '3.3'

services: 
    wordpress:
        build: .
        restart: always
        ports: 
            - 8080:80
        environment: 
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wpuser
            WORDPRESS_DB_PASSWORD: wppass
            WORDPRESS_DB_NAME: wpdb
        volumes: 
            - ./src/plugins:/var/www/html/wp-content/plugins/
            - ./src/app:/var/www/html/wp-content/themes/

    db:
        image: mysql:5.7
        restart: always
        environment: 
            MYSQL_DATABASE: wpdb
            MYSQL_USER: wpuser
            MYSQL_PASSWORD: wppass
            MYSQL_ROOT_PASSWORD: password
        volumes: 
            - db:/var/lib/mysql

    adminer:
        depends_on: 
            - db
        image: adminer
        restart: always
        ports: 
            - 8888:8080
    app:
        image: phpmyadmin/phpmyadmin:latest
        links:
          - db
        ports:
          - 9090:9090
        environment:
          - PMA_ARBITRARY=1

networks: 
    back:
        
volumes: 
    db: